apiVersion: v2
name: auth-ui
description: A Helm chart for auth-ui service
type: application
version: 1.10.0
appVersion: 1.10.0
dependencies:
  - name: mc-labels-and-annotations
    version: 0.8.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
