apiVersion: v2
name: auth-manager
description: A Helm chart for auth-manager service
type: application
version: 1.11.0
appVersion: 1.11.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
