apiVersion: v2
name: token-kiosk
description: A Helm chart for token-kiosk service
type: application
version: 1.12.0
appVersion: 1.12.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
