apiVersion: v2
name: opa
description: A Helm chart for opa
type: application
version: 1.10.0
appVersion: 1.0.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
