apiVersion: v2
name: opa
description: A Helm chart for opa
type: application
version: 1.10.0
appVersion: 1.0.1
dependencies:
  - name: mc-labels-and-annotations
    version: 0.8.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
