apiVersion: v2
name: auth-cron
description: A Helm chart for auth-cron service
type: application
version: 1.12.0
appVersion: 1.12.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
